services:
  wildfly-docker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: wildfly-docker
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9990:9990"
      - "4447:4447"
      - "8009:8009"
    networks:
      - ejb-network
    volumes:
      - ./wildfly-data:/opt/jboss/wildfly/standalone/data:rw
    environment:
      - JAVA_OPTS=-Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0 -Ddevises.file=/opt/jboss/wildfly/standalone/data/devises.txt

networks:
  ejb-network:
    driver: bridge